---
# tasks file for gschaetz.provision-desktop
- include_vars:
    file: "{{ application_setup }}"
    name: apps

# delete desktop entries
- name: Delete all desktop files 
  shell: "rm -rf {{ local_home }}/Desktop/*.desktop"
  become: true
  become_method: sudo

# # remove custom menu items
- name: Delete all desktop files 
  shell: "rm -rf /usr/share/applications/*-myapps.desktop"
  become: true

# remove main directory
- name: Remove main directory
  file: path={{ desktop_dir }}/apps/ state=absent

# create main directory
- name: Creates main directory
  file: path={{ desktop_dir }}/apps/ state=directory

# create persistent directories for applications
- name: Creates persistent app directories
  file: path={{ desktop_dir }}/persistent/{{ item.key }} state=directory mode=0777
  #become: true
  with_dict: "{{ apps.applications | default({}) }}"
  when: apps.applications is defined

# create resources directory
- name: Creates resource directory
  file: path={{ desktop_dir }}/resources state=directory

# remove fast links directory
- name: Remove links directory
  file: path=/usr/local/bin/myapps/ state=absent
  become: true

# create fast links directory
- name: Create links directory
  file: path=/usr/local/bin/myapps/ state=directory
  become: true

# create directories for applications
- name: Creates application directories
  file: path={{ desktop_dir }}/apps/{{ item.key }} state=directory
  with_dict: "{{ apps.applications | default({}) }}"
  when: apps.applications is defined

# LINUX (NOT WSL)
# download app icons for linux but not wsl
- name: Download app icons
  get_url:
    url: "{{ item.value.desktop_icon_download_url }}"
    dest: "{{ desktop_dir }}/apps/{{ item.key }}/{{ item.value.desktop_icon | default(item.key + '.png') }}"
    mode: 0440 
  with_dict: "{{ apps.applications | default({}) }}"
  when: 
    - apps.applications is defined and ansible_system == 'Linux' and WSL_LINUX == 'FALSE'
    - item.value.show_on_desktop|default(false) == true 

# download sec comps
- name: Download sec comps
  get_url:
    url: "{{ item.value.docker_sec_comp_download_url }}"
    dest: "{{ desktop_dir }}/apps/{{ item.key }}/{{ item.key }}.json"
    mode: 0440
  when: apps.applications is defined and item.value.docker_sec_comp|default(false) == true
  with_dict: "{{ apps.applications | default({}) }}"

# LINUX (NOT WSL)
# create desktop icon on Linux 
- name: Create desktop icon
  template:
    src: "{{ project_home }}/templates/gnome-desktop-template.j2"
    dest: "{{ local_home }}/Desktop/{{ item.value.desktop_name | default(item.key) }}.desktop"
    mode: 0777
  when: apps.applications is defined and item.value.show_on_desktop|default(false) == true and ansible_system == 'Linux' and WSL_LINUX == 'FALSE'
  with_dict: "{{ apps.applications | default({}) }}"

# LINUX AND NOT WSL
# # create menu item on linux
- name: Create menu item
  template:
    src: "{{ project_home }}/templates/gnome-desktop-template.j2"
    dest: "/usr/share/applications/{{ item.value.desktop_name | default(item.key) }}-myapps.desktop"
    mode: 0777
  become: true
  with_dict: "{{ apps.applications | default({}) }}"
  when: 
    - apps.applications is defined and ansible_system == 'Linux' and WSL_LINUX == 'FALSE'
    - item.value.menu_category is defined

# LINUX AND NOT WSL
# gio those apps
- name: gio the apps to remove untrusted
  shell: gio set {{ local_home }}/Desktop/{{ item.value.desktop_name | default(item.key) }}.desktop "metadata::trusted" yes
  when: apps.applications is defined and item.value.show_on_desktop|default(false) == true and ansible_system == 'Linux' and WSL_LINUX == 'FALSE'
  with_dict: "{{ apps.applications | default({}) }}" 

# LINUX AND NOT WSL
# add xhost + to ensure x can run 
- name: xhost +
  shell: xhost +
  when: ansible_system == 'Linux' and WSL_LINUX == 'FALSE'
  ignore_errors: true

# LINUX OR WSL
# create docker start files 
- name: Linux/WSL, create docker start file
  template:
    src: "{{ project_home }}/templates/app-start-docker.j2"
    dest: "{{ desktop_dir }}/apps/{{ item.key }}/{{ item.key }}"
    mode: 0770
  when: item.value.implementation_type == "docker" and apps.applications is defined and ansible_system == 'Linux'
  with_dict: "{{ apps.applications | default({}) }}"

# MAC ONLY
# create docker start files 
- name: MAC, create docker start file
  template:
    src: "{{ project_home }}/templates/app-start-docker-macos.j2"
    dest: "{{ desktop_dir }}/apps/{{ item.key }}/{{ item.key }}"
    mode: 0770
  when: item.value.implementation_type == "docker" and apps.applications is defined and ansible_system == 'Darwin' 
  with_dict: "{{ apps.applications | default({}) }}"

# create docker_compose file
- name: create docker_compose file
  template:
    src: "{{ project_home }}/templates/app-dockercompose.j2"
    dest: "{{ desktop_dir }}/apps/{{ item.key }}/docker-compose.yml"
    mode: 0770
  when: item.value.implementation_type == "docker_compose" and apps.applications is defined 
  with_dict: "{{ apps.applications | default({}) }}"

# create docker_compose files 
- name: create docker_compose run file
  template:
    src: "{{ project_home }}/templates/app-start-dockercompose.j2"
    dest: "{{ desktop_dir }}/apps/{{ item.key }}/{{ item.key }}"
    mode: 0770
  when: item.value.implementation_type == "dockershow_on_desktop_compose" and apps.applications is defined  
  with_dict: "{{ apps.applications | default({}) }}"

# create link for command line runfile:
- name: create link for bin
  file: 
    src: "{{ desktop_dir }}/apps/{{ item.key }}/{{ item.key }}"
    dest: "/usr/local/bin/myapps/{{ item.key }}"
    state: link
  become: true
  with_dict: "{{ apps.applications | default({}) }}"

# create /etc/profile.d/ directory on mac
- name: Creates /etc/profile.d directory
  file: path='/etc/profile.d/' state=directory
  become: true
  when: ansible_system == 'Darwin'

# create a file in /etc/profile.d
- name: create file in path for env 
  copy: 
    content: "PATH=/usr/local/bin/myapps/:$PATH" 
    dest: "/etc/profile.d/custom-path.sh"
  become: true
