#OPTION                         VALUE                                                   DEFAULT
#implementation_type            docker|docker_compose|dockershow_on_desktop_compose     Required    
#docker_image                   'string: image location'                                Required
#desktop_icon_download_url      'string: image url for download'                        Required 
#menu_category                  'string: Gnome category for app'                        Required
#docker_ports                   'string: -p port1:port1 -p port2:port2'                 defaults to none
#docker_volumes                 'string: -v volume1 -v  volume2'                        defaults to none
#show_on_desktop                true|false                                              defaults to false
#desktop_exec                   'string: executable name'                               defaults to key (e.g. firefox:)
#desktop_name                   'string: name on desktop'                               defaults to key (e.g. firefox:)
#desktop_icon                   'string: name of app icon'                              defaults to key with a png extension (e.g. firefox.png)
#gui_app                        true|false                                              defaults true
#pulse_audio                    true|false                                              defaults false
#snd                            true|false                                              defaults false
#docker_network                 'string: docker network'                                defaults to host
#share_themes                   true|false                                              defaults to true
#container_home                 'string: home path in container'                        defaults to /home/user
#app_persistent_dir             'string: container path to persist'                     defaults to none
#app_persistent_download_dir    'string: container download path persist'               defaults to none
#extra_docker_flags             'string: any extra docker flags'                        defaults to none
#docker_sec_comp                true|false                                              defaults to false
#docker_sec_comp_download_url   'string: url to download sec_comp'                      defaults to none|required if docker_sec_comp is true
#docker_entrypoint              'string: override docker entrypoint'                    defaults to none
#time_synchronization           true|false                                              defaults to true
#share_host_memory              true|false                                              defaults to false
#docker_entrypoint_command      'string: run command with docker image'                 defaults to none
---         
applications:
    firefox:
        implementation_type: docker
        docker_image: jess/firefox:latest
        docker_volumes: -v /:/host_drive
        desktop_icon_download_url: https://findicons.com/files/icons/1070/software/128/mozilla_firefox.png
        menu_category: Network;WebBrowser;
        extra_docker_flags: --cpus 2 --device /dev/dri
        app_persistent_dir: /home/user
        app_persistent_download_dir: /home/user/Downloads
        share_host_memory: true
        pulse_audio: true
    wargames:
        implementation_type: docker
        docker_image: jess/wargames:latest
        desktop_icon_download_url: https://cdn.iconscout.com/icon/free/png-256/wargaming-1-283119.png
        menu_category: Network;Game;
        gui_app: false
        share_themes: false
    chrome:
        implementation_type: docker
        docker_image: jess/chrome:latest
        docker_volumes: -v /:/host_drive
        desktop_icon_download_url: http://icons.iconarchive.com/icons/google/chrome/128/Google-Chrome-icon.png
        menu_category: Network;WebBrowser;
        extra_docker_flags: --cpus 1 --memory 1024mb --device /dev/dri 
        docker_sec_comp: true
        docker_sec_comp_download_url: https://raw.githubusercontent.com/jfrazelle/dotfiles/master/etc/docker/seccomp/chrome.json
        app_persistent_dir: /data
        app_persistent_download_dir: /home/chrome/Downloads/
        container_home: /home/chrome/ 
        share_host_memory: true
    vscode:
        implementation_type: docker
        docker_image: jess/vscode:latest
        docker_volumes: -v /:/host_drive -v /var/run/docker.sock:/var/run/docker.sock
        desktop_icon_download_url: https://upload.wikimedia.org/wikipedia/commons/f/f3/Visual_Studio_Code_0.10.1_icon.png
        menu_category: Development;IDE;
        extra_docker_flags: --cpus 1 --memory 1024mb 
        app_persistent_dir: /home/user/
        pulse_audio: true
    wordpress_compose:
        implementation_type: docker_compose
        show_on_desktop: true
        desktop_name: wordpress_compose
        desktop_exec: wordpress_compose
        desktop_icon_download_url: http://icons.iconarchive.com/icons/graphics-vibe/simple-rounded-social/128/wordpress-icon.png
        desktop_icon: wordpress_compose.png
        menu_category: Network;WebBrowser;
        gui_app: true
        pulse_audio: false
        compose_version: "version: '2'"
        compose_network: dev
        compose_definition:
            services:
                db:
                    image: mysql:5.7
                    volumes:
                        - dbdata:/var/lib/mysql
                    restart: always
                    environment:
                        MYSQL_ROOT_PASSWORD: somewordpress
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: wordpress
                wordpress:
                    depends_on:
                        - db
                    image: wordpress:latest
                    ports:
                        - "8000:80"
                    restart: always
                    environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: wordpress
            volumes:
                dbdata:
