#OPTION                         VALUE                                         DEFAULT
#implementation_type            docker|docker_compose|                         Required    
#docker_image                   'string: image location'                      Required
#docker_ports                   'string: -p port1:port1 -p port2:port2'       defaults to none
#docker_volumes                 'string: -v volume1 -v  volume2'              defaults to none
#desktop_exec                   'string: executable name'                     defaults to key (e.g. firefox:)
#gui_app                        true|false                                    defaults true
#docker_network                 'string: docker network'                      defaults to host
#container_home                 'string: home path in container'              defaults to /home/user
#app_persistent_dir             'string: container path to persist'           defaults to none
#app_persistent_download_dir    'string: container download path persist'     defaults to none
#extra_docker_flags             'string: any extra docker flags'              defaults to none
#docker_sec_comp                true|false                                    defaults to false
#docker_sec_comp_download_url   'string: url to download sec_comp'            defaults to none|required if docker_sec_comp is true
#docker_entrypoint              'string: override docker entrypoint'          defaults to none
#docker_entrypoint_command      'string: run command with docker image'       defaults to none
---
applications:
    firefox:
        implementation_type: docker
        docker_image: jess/firefox:latest
        docker_volumes: -v /:/host_drive
        extra_docker_flags: --cpus 2
        app_persistent_dir: /home/user
        app_persistent_download_dir: /home/user/Downloads
    wargames:
        implementation_type: docker
        docker_image: jess/wargames:latest
        gui_app: false
    wordpress_compose:
        implementation_type: docker_compose
        gui_app: true
        compose_version: "version: '2'"
        compose_network: dev
        compose_definition:
            services:
                db:
                    image: mysql:5.7
                    volumes:
                        - dbdata:/var/lib/mysql
                    restart: always
                    environment:
                        MYSQL_ROOT_PASSWORD: somewordpress
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: wordpress
                wordpress:
                    depends_on:
                        - db
                    image: wordpress:latest
                    ports:
                        - "8000:80"
                    restart: always
                    environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: wordpress
            volumes:
                dbdata:
